### ISSUE TITLE
READMEにアプリの説明や環境情報、使い方を明記する

### ISSUE THREAD

**Issue by norotime** [rychr0327/runstep#1]
https://github.com/rychr0327/runstep/blob/master/README.md

@rychr0327 模範例はこちら。
https://github.com/masarusan24/hanaguri-silver/blob/develop/README.md

**Comment by rychr0327** [comment]
修正しました。

**Comment by norotime** [comment]
@rychr0327 修正した場合は、コミットメッセージでクローズする方法でイシューを閉じていただけますか？

**Comment by norotime** [comment]
https://help.github.com/articles/closing-issues-using-keywords/
